services:
  bot:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    profiles:
      - prod

  bot-dev:
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
    profiles:
      - dev
